# Generated by Django 3.2 on 2021-05-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
