# Generated by Django 3.2 on 2021-05-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210522_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biometric_data',
            field=models.TextField(),
        ),
    ]
